// <auto-generated />
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ETG.SABENTISpro.Models.Core.Session
{

    // CORE_SESSIONS
    [Table("CORE_USER", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.0.0")]
    public partial class CORE_USER
    {
        /// <summary>
        /// 
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"id", Order = 1, TypeName = "uniqueidentifier")]
        [Index(@"PK_CORE_SESSIONS", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public System.Guid id { get; set; } // id (Primary key)

        /// <summary>
        /// 
        /// </summary>
        [Column(@"started", Order = 2, TypeName = "bigint")]
        [Required]
        [Display(Name = "Started")]
        public long started { get; set; } // started

        /// <summary>
        /// 
        /// </summary>
        [Column(@"lastrefresh", Order = 3, TypeName = "bigint")]
        [Required]
        [Display(Name = "Lastrefresh")]
        public long lastrefresh { get; set; } // lastrefresh

        /// <summary>
        /// 
        /// </summary>
        [Column(@"device", Order = 4, TypeName = "nvarchar")]
        [MaxLength(255)]
        [StringLength(255)]
        [Display(Name = "Device")]
        public string device { get; set; } // device (length: 255)

        /// <summary>
        /// 
        /// </summary>
        [Column(@"expires", Order = 5, TypeName = "bigint")]
        [Required]
        [Display(Name = "Expires")]
        public long expires { get; set; } // expires

        /// <summary>
        /// 
        /// </summary>
        [Column(@"uuid", Order = 6, TypeName = "uniqueidentifier")]
        [Required]
        [Display(Name = "Uuid")]
        public System.Guid uuid { get; set; } // uuid

        /// <summary>
        /// 
        /// </summary>
        [Column(@"data", Order = 7, TypeName = "nvarchar(max)")]
        [Display(Name = "Data")]
        public string data { get; set; } // data

        /// <summary>
        /// 
        /// </summary>
        public CORE_USER()
        {
            InitializePartial();
        }

        /// <summary>
        /// 
        /// </summary>
        partial void InitializePartial();
    }

}